name: hominode_sos
description: Trusted live emergency assistance UI and client for Hominode.
version: 1.0.0
publish_to: none
environment:
  sdk: '>=3.9.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: '>=5.4.4 <7.0.0'
  cloud_functions: '>=5.6.2 <7.0.0'
  url_launcher: ^6.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
